apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  namespace: petclinic
spec:
  selector:
    app: petclinic-server
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30088
